### PR TITLE
ART-11334: exclude v2 to ignore

### PR DESCRIPTION
**Pull request by mbiarnes**
@nrb  this PR is for fixing

            error: go: go.mod file not found in current directory or any parent

### CODE REVIEW

**Comment by RadekManak** [comment]
Hello, @mbiarnes Change the commit to "UPSTREAM: <carry>: exclude v2 to ignore". 
This is for our rebasebot automation to cherry-pick the commit in next rebase.

Instead of <carry> upstream PR is used when there is one. If this is a downstream carry patch <carry> is used.

I don't have context on this but looks like this file is trying to solve the same issue. Maybe the filename is wrong?
https://github.com/openshift/azure-service-operator/blob/main/openshift/Dockerfile.dockerignore

**Comment by mbiarnes** [comment]
@JoelSpeed can you approve this?

**Comment by shellyyang1989** [comment]
Joel is on PTO. @RadekManak could you please approve it? Thank you!

**Comment by RadekManak** [comment]
Where are you getting this error? The .dockerignore file you are modifying should be ignored by the tooling and instead the more specific `openshift/Dockerfile.dockerignore` for `openshift/Dockerfile` should be used.

I was able to reproduce your error by
```
rm openshift/Dockerfile.dockerignore
podman build -f openshift/Dockerfile .
```
Then the .dockerfile from project root was used. Is there some miconfiguration? Or maybe .dockerignore is used somehow when importing the repository?

**Comment by joepvd** [comment]
How the repo gets offered to the OSBS (and konflux) build systems is:

- clone this repo
- copy specified Dockerfile to the root of the repo
- (set some base images, do some build system configuration)
- trigger a build

So effectively, the Dockerfile from the root of this repo gets overwritten by the `openshift/Dockerfile` repo, which makes the `.dockerignore` bite :)

**Comment by RadekManak** [comment]
I have proposed alternative PR that will override the upstream .dockerignore with our version.

**Comment by mbiarnes** [comment]
@RadekManak will run a test build with these changes

**Comment by mbiarnes** [comment]
@RadekManak 
the test build with the changes propoese in #5 was SUCCESSFUL
https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=3403020
@joepvd if there are no objections I will close this PR when #5 was merged

**Comment by JoelSpeed** [comment]
#5 merged, this is no longer needed

**Pull request closed without merging**
