### PR TITLE
ART-11334: Replace .dockerignore with openshift version

### PR DESCRIPTION
**Pull request by RadekManak**
Alternative for #4

This PR adds make target that copies openshift/.dockerignore to .dockerignore.

This make target will need to be added as a lifecyclehook script to be run after every rebase to avoid conflicts.

cc: @damdo @nrb

### CODE REVIEW

**Comment by mbiarnes** [comment]
@RadekManak 
test build was successful with your changes: https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=3403020

**Comment by RadekManak** [comment]
Renamed. I wanted to make the target more generic to make it extendable, but we can change it later or add a parent target if we need to in the future.

**Comment by RadekManak** [comment]
/override ci/prow/e2e-azure-ovn-techpreview
Does not test this change.

**Comment by nrb** [comment]
/lgtm

Thanks @RadekManak and @mbiarnes for tackling this. We learned something about OSBS in this process :)

**Review by damdo — COMMENTED** [review]
/lgtm

/assing @nrb

**Pull request merged**
